FROM node:20-alpine3.17 as build

WORKDIR /usr/src/app

ARG REACT_APP_ALCHEMY_API_KEY
ARG REACT_APP_0x_API_KEY
ENV REACT_APP_ALCHEMY_API_KEY $REACT_APP_ALCHEMY_API_KEY
ENV REACT_APP_0x_API_KEY $REACT_APP_0x_API_KEY

COPY package.json package-lock.json ./

RUN npm install

COPY . .

RUN npm run build

FROM nginx
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /usr/src/app/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]